/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/_layout'
import { Route as AuthenticatedLayoutDashboardRouteImport } from './routes/_authenticated/_layout/dashboard'
import { Route as AuthenticatedLayoutAppointmentsRouteImport } from './routes/_authenticated/_layout/appointments'
import { Route as AuthenticatedLayoutAppointmentsBookRouteImport } from './routes/_authenticated/_layout/appointments/book'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLayoutDashboardRoute =
  AuthenticatedLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutAppointmentsRoute =
  AuthenticatedLayoutAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutAppointmentsBookRoute =
  AuthenticatedLayoutAppointmentsBookRouteImport.update({
    id: '/book',
    path: '/book',
    getParentRoute: () => AuthenticatedLayoutAppointmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/appointments': typeof AuthenticatedLayoutAppointmentsRouteWithChildren
  '/dashboard': typeof AuthenticatedLayoutDashboardRoute
  '/appointments/book': typeof AuthenticatedLayoutAppointmentsBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/appointments': typeof AuthenticatedLayoutAppointmentsRouteWithChildren
  '/dashboard': typeof AuthenticatedLayoutDashboardRoute
  '/appointments/book': typeof AuthenticatedLayoutAppointmentsBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/_layout': typeof AuthenticatedLayoutRouteWithChildren
  '/_authenticated/_layout/appointments': typeof AuthenticatedLayoutAppointmentsRouteWithChildren
  '/_authenticated/_layout/dashboard': typeof AuthenticatedLayoutDashboardRoute
  '/_authenticated/_layout/appointments/book': typeof AuthenticatedLayoutAppointmentsBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/register'
    | '/appointments'
    | '/dashboard'
    | '/appointments/book'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/register'
    | '/appointments'
    | '/dashboard'
    | '/appointments/book'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/_layout'
    | '/_authenticated/_layout/appointments'
    | '/_authenticated/_layout/dashboard'
    | '/_authenticated/_layout/appointments/book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_layout/dashboard': {
      id: '/_authenticated/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedLayoutDashboardRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/appointments': {
      id: '/_authenticated/_layout/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedLayoutAppointmentsRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/appointments/book': {
      id: '/_authenticated/_layout/appointments/book'
      path: '/book'
      fullPath: '/appointments/book'
      preLoaderRoute: typeof AuthenticatedLayoutAppointmentsBookRouteImport
      parentRoute: typeof AuthenticatedLayoutAppointmentsRoute
    }
  }
}

interface AuthenticatedLayoutAppointmentsRouteChildren {
  AuthenticatedLayoutAppointmentsBookRoute: typeof AuthenticatedLayoutAppointmentsBookRoute
}

const AuthenticatedLayoutAppointmentsRouteChildren: AuthenticatedLayoutAppointmentsRouteChildren =
  {
    AuthenticatedLayoutAppointmentsBookRoute:
      AuthenticatedLayoutAppointmentsBookRoute,
  }

const AuthenticatedLayoutAppointmentsRouteWithChildren =
  AuthenticatedLayoutAppointmentsRoute._addFileChildren(
    AuthenticatedLayoutAppointmentsRouteChildren,
  )

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedLayoutAppointmentsRoute: typeof AuthenticatedLayoutAppointmentsRouteWithChildren
  AuthenticatedLayoutDashboardRoute: typeof AuthenticatedLayoutDashboardRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedLayoutAppointmentsRoute:
    AuthenticatedLayoutAppointmentsRouteWithChildren,
  AuthenticatedLayoutDashboardRoute: AuthenticatedLayoutDashboardRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
