"""Add debug columns to voice_call_records

Revision ID: ecdb9f35bb3e
Revises: 001_initial
Create Date: 2025-12-07 16:39:56.596254
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecdb9f35bb3e'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.alter_column('appointments', 'appointment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('appointments', 'confirmed_by_patient',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('appointments', 'confirmed_by_doctor',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('appointments', 'is_virtual',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('appointments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_appointments_confirmation_code', 'appointments', type_='unique')
    op.drop_index('ix_appointments_confirmation_code', table_name='appointments')
    op.create_index(op.f('ix_appointments_confirmation_code'), 'appointments', ['confirmation_code'], unique=True)
    op.alter_column('audit_logs', 'old_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'contains_phi',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('doctors', 'working_hours',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('doctors', 'buffer_time_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Buffer time between appointments in minutes',
               existing_server_default=sa.text('15'))
    op.alter_column('doctors', 'appointment_duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Default appointment slot duration',
               existing_server_default=sa.text('30'))
    op.alter_column('doctors', 'max_patients_per_day',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('20'))
    op.alter_column('doctors', 'clinic_id',
               existing_type=sa.UUID(),
               comment='Reference to clinic table if multi-clinic support added',
               existing_nullable=True)
    op.alter_column('doctors', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('doctors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('doctors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_doctors_license_number', 'doctors', type_='unique')
    op.create_index(op.f('ix_doctors_license_number'), 'doctors', ['license_number'], unique=True)
    op.alter_column('notifications', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.alter_column('notifications', 'delivery_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('notifications', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('patients', 'medical_history',
               existing_type=sa.TEXT(),
               comment='Encrypted PHI',
               existing_nullable=True)
    op.alter_column('patients', 'allergies',
               existing_type=sa.TEXT(),
               comment='Encrypted PHI',
               existing_nullable=True)
    op.alter_column('patients', 'medications',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='Encrypted PHI - list of current medications',
               existing_nullable=True)
    op.alter_column('patients', 'emergency_contact',
               existing_type=sa.VARCHAR(length=255),
               comment='Encrypted PHI',
               existing_nullable=True)
    op.alter_column('patients', 'preferred_contact_method',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'sms'::character varying"))
    op.alter_column('patients', 'sms_consent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('patients', 'email_consent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('patients', 'call_consent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('patients', 'encrypted_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='Tracks which fields are encrypted',
               existing_nullable=True)
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('patients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_patients_user_id', table_name='patients')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_constraint('uq_users_phone_number', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_phone_number', table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.add_column('voice_call_records', sa.Column('debug_trace', sa.JSON(), nullable=True))
    op.add_column('voice_call_records', sa.Column('latency_metrics', sa.JSON(), nullable=True))
    op.add_column('voice_call_records', sa.Column('sentiment_timeline', sa.JSON(), nullable=True))
    op.alter_column('voice_call_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('voice_call_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_voice_call_records_call_sid', 'voice_call_records', type_='unique')
    op.drop_index('ix_voice_call_records_call_sid', table_name='voice_call_records')
    op.create_index(op.f('ix_voice_call_records_call_sid'), 'voice_call_records', ['call_sid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_call_records_call_sid'), table_name='voice_call_records')
    op.create_index('ix_voice_call_records_call_sid', 'voice_call_records', ['call_sid'], unique=False)
    op.create_unique_constraint('uq_voice_call_records_call_sid', 'voice_call_records', ['call_sid'])
    op.alter_column('voice_call_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('voice_call_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('voice_call_records', 'sentiment_timeline')
    op.drop_column('voice_call_records', 'latency_metrics')
    op.drop_column('voice_call_records', 'debug_trace')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('uq_users_phone_number', 'users', ['phone_number'])
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_patients_user_id', 'patients', ['user_id'], unique=False)
    op.alter_column('patients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('patients', 'encrypted_fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Tracks which fields are encrypted',
               existing_nullable=True)
    op.alter_column('patients', 'call_consent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('patients', 'email_consent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('patients', 'sms_consent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('patients', 'preferred_contact_method',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'sms'::character varying"))
    op.alter_column('patients', 'emergency_contact',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Encrypted PHI',
               existing_nullable=True)
    op.alter_column('patients', 'medications',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Encrypted PHI - list of current medications',
               existing_nullable=True)
    op.alter_column('patients', 'allergies',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Encrypted PHI',
               existing_nullable=True)
    op.alter_column('patients', 'medical_history',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Encrypted PHI',
               existing_nullable=True)
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('notifications', 'delivery_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('notifications', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.drop_index(op.f('ix_doctors_license_number'), table_name='doctors')
    op.create_unique_constraint('uq_doctors_license_number', 'doctors', ['license_number'])
    op.alter_column('doctors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('doctors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('doctors', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('doctors', 'clinic_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to clinic table if multi-clinic support added',
               existing_nullable=True)
    op.alter_column('doctors', 'max_patients_per_day',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('20'))
    op.alter_column('doctors', 'appointment_duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='Default appointment slot duration',
               existing_server_default=sa.text('30'))
    op.alter_column('doctors', 'buffer_time_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='Buffer time between appointments in minutes',
               existing_server_default=sa.text('15'))
    op.alter_column('doctors', 'working_hours',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('audit_logs', 'contains_phi',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('audit_logs', 'new_values',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_values',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_appointments_confirmation_code'), table_name='appointments')
    op.create_index('ix_appointments_confirmation_code', 'appointments', ['confirmation_code'], unique=False)
    op.create_unique_constraint('uq_appointments_confirmation_code', 'appointments', ['confirmation_code'])
    op.alter_column('appointments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('appointments', 'is_virtual',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('appointments', 'confirmed_by_doctor',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('appointments', 'confirmed_by_patient',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('appointments', 'appointment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'scheduled'::character varying"))
    # ### end Alembic commands ###
